const ACTION_TYPES = {
    API_PENDING: 'SERVICE_PENDING',
    API_SUCCESS: 'SERVICE_SUCCESS',
    API_ERROR: 'SERVICE_ERROR',
    API_NAV1:'CHANGE_NAV_REC',
    API_NAV2:'CHANGE_NAV_NEWS',
    MERGE_POPUP:'MERGE_POPUP1',
    MERGE_POPUP2:'MERGE_POPUP_SECTION',
    REMOVE_POPUP:'REMOVE_POPUP',
    REMOVE_POPUP2:'REMOVE_POPUP_SECTION',
    COLLSEC_POPUP:'COLLSEC_POPUP',
    PINS_REMOVE:'PINS_REMOVE',
    UNDO:'UNDO',
    ADD_cOL:'ADD_COL',
    CHECKLOGIN: 'CHECKLOGIN',
    CHECKLOGOUT: 'CHECKLOGOUT',
    SEC_EDIT_POPUP: 'SEC_EDIT_POPUP',

  };
  export default ACTION_TYPES;